/**
 * Generate fixed-weight wrappers for the installed Phosphor icon catalog.
 *
 * @file      GeneratePhosphorIcons.mjs
 * @author    Gage Sorrell <gage@sorrell.sh>
 * @copyright (c) 2026 Gage Sorrell
 * @license   MIT
 */

import { readdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const PackageDirectory = dirname(dirname(fileURLToPath(import.meta.url)));
const PhosphorDirectory = dirname(fileURLToPath(import.meta.resolve(
    "@phosphor-icons/react/package.json"
)));
const CatalogDirectory = join(PhosphorDirectory, "dist", "ssr");
const OutputDirectory = join(PackageDirectory, "Source", "PhosphorIcon");
const Icons = readdirSync(CatalogDirectory)
    .filter(Name => Name.endsWith(".d.ts") && Name !== "index.d.ts")
    .map(Name => Name.slice(0, -5))
    .sort((Left, Right) => Left.localeCompare(Right));
const Styles = [ "Bold", "Duotone", "Fill", "Light", "Regular", "Thin" ];

for (const Style of Styles)
{
    const Weight = Style.toLowerCase();
    const Exports = Icons.map(Name =>
        `export const ${ Name }Icon = CreatePhosphorIcon("${ Name }Icon", "${ Weight }");`
    ).join("\n");
    const Content = `/**
 * One-cell ${ Weight } Phosphor icons.
 *
 * Generated by Script/GeneratePhosphorIcons.mjs. Do not edit manually.
 *
 * @module @sorrell/ink-ui/PhosphorIcon/${ Style }
 *
 * @file      ${ Style }.ts
 * @author    Gage Sorrell <gage@sorrell.sh>
 * @copyright (c) 2026 Gage Sorrell
 * @license   MIT
 */

import { CreatePhosphorIcon } from "./Internal.js";

/* eslint-disable @stylistic/max-len */

${ Exports }
`;

    writeFileSync(join(OutputDirectory, `${ Style }.ts`), Content);
}

console.log(`Generated ${ Icons.length } icons in ${ Styles.length } styles.`);
