/**
 * Embed the font catalog from a local checkout of superstarryeyes/bit.
 *
 * @file      GenerateBitFonts.mjs
 * @author    Gage Sorrell <gage@sorrell.sh>
 * @copyright (c) 2026 Gage Sorrell
 * @license   MIT
 */

import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { stdout } from "node:process";
import { fileURLToPath } from "node:url";

const PackageDirectory = dirname(dirname(fileURLToPath(import.meta.url)));
const MonorepoDirectory = dirname(dirname(PackageDirectory));
const FontDirectory = join(MonorepoDirectory, "bit", "ansifonts", "fonts");
const OutputPath = join(PackageDirectory, "Source", "Display", "Fonts.generated.ts");
const Fonts = readdirSync(FontDirectory)
    .filter((Name) => Name.endsWith(".bit"))
    .map((Name) => JSON.parse(readFileSync(join(FontDirectory, Name), "utf8")))
    .sort((Left, Right) => Left.name.localeCompare(Right.name));
const Names = Fonts.map((Font) => Font.name);
const Catalog = Object.fromEntries(Fonts.map((Font) => [ Font.name, Font ]));
const Content = `/**
 * Embedded bitmap fonts from superstarryeyes/bit.
 *
 * Generated by Script/GenerateBitFonts.mjs. Do not edit manually.
 * Each font's upstream author and license remain available in its metadata.
 *
 * @module @sorrell/ink-ui/Display/Fonts
 *
 * @file      Fonts.generated.ts
 * @author    Gage Sorrell <gage@sorrell.sh>
 * @copyright (c) 2026 Gage Sorrell
 * @license   MIT
 */

/* eslint-disable @stylistic/max-len */

export interface DisplayFont
{
    readonly Name: string;
    readonly Author: string;
    readonly License: string;
    readonly Characters: Readonly<Record<string, ReadonlyArray<string>>>;
}

export const DisplayFontFamilies = [ ${ Names.map((Name) => JSON.stringify(Name)).join(", ") } ] as const;

export type DisplayFontFamily = typeof DisplayFontFamilies[number];

export const DefaultDisplayFontFamily: DisplayFontFamily = DisplayFontFamilies[0];

interface SerializedFont
{
    readonly name: string;
    readonly author: string;
    readonly license: string;
    readonly characters: Readonly<Record<string, ReadonlyArray<string>>>;
}

const SerializedFonts: string = ${ JSON.stringify(JSON.stringify(Catalog)) };
const FontCatalog = JSON.parse(SerializedFonts) as Readonly<Record<DisplayFontFamily, SerializedFont>>;

/** Look up a bundled bit font and its upstream metadata. */
export function GetDisplayFont(FontFamily: DisplayFontFamily): DisplayFont
{
    const Font: SerializedFont = FontCatalog[FontFamily];
    return {
        Author: Font.author,
        Characters: Font.characters,
        License: Font.license,
        Name: Font.name
    };
}
`;

writeFileSync(OutputPath, Content);
stdout.write(`Generated ${ Fonts.length } embedded bit fonts.\n`);
