/**
 * @file      Config.ts
 * @author    Gage Sorrell <gage@sorrell.sh>
 * @copyright (c) 2026 Gage Sorrell
 * @license   MIT
 */

import { $SchemaKey } from "../../Shared/Config/Config.js";
import type { CodeFormatter } from "./Config.Types.js";
import type { ConfigSchema } from "../../Shared/Config/Config.Types.ts";
import { Schema as EffectSchema } from "effect";

export const CodeFormatters: ReadonlyArray<CodeFormatter> =
    [
        "eslint",
        "ox",
        "prettier"
    ] as const;

/* eslint-disable @typescript-eslint/typedef */

export const Provider = EffectSchema.Struct({
    Enabled: EffectSchema.Boolean
        .annotateKey({
            default: true,
            description: (
                "Whether the provider's augmentation is generated when `code-auger generate` runs."
            ),
            title: "enabled"
        }),
    Watch: EffectSchema.optionalKey(EffectSchema.Boolean)
        .annotateKey({
            default: true,
            description: (
                "Whether this provider's module should be generated by `code-auger` when " +
                "the `--watch` flag is specified."
            ),
            title: "watch"
        })
}).annotate({
    default: { Enabled: true, Watch: true } as const,
    description: "For a given consumer and given provider, the consumer's configuration of that provider.",
    identifier: "Provider",
    title: "Provider"
});

export/**
       * The config of a given provider package specifies the types and export paths
       * relevant to generating the augmenting module for consumers that use the given
       * provider.
       */
const Schema = EffectSchema.Struct({
    [ $SchemaKey ]: EffectSchema.Literal("code-auger/schema")
        .annotateKey({
            default: "code-auger/schema",
            description: "The JSON schema for this config file.",
            title: "$schema"
        }),
    BasePath: EffectSchema.NonEmptyString
        .annotateKey({
            description: (
                "The directory path in which `code-auger` will write the modules " +
                "generated by your installed providers."
            ),
            title: "basePath"
        }),
    DisabledFormatters: EffectSchema.optionalKey(EffectSchema.Array(EffectSchema.Literals(CodeFormatters)))
        .annotateKey({
            description: (
                "If specified, the formatters/linters that `code-auger` will disable for its " +
                "generated modules.  ESLint and oxfmt/oxlint are disabled via top-level comments in " +
                "the generated modules."
            ),
            title: "disabledFormatters"
        }),
    PrependedLines: EffectSchema.optionalKey(EffectSchema.Array(EffectSchema.String))
        .annotateKey({
            description: (
                "If specified, these lines of text will be prepended to all " +
                "modules generated by `code-auger`."
            ),
            title: "prependedLines"
        }),
    PrependedLinesOrder: EffectSchema.optionalKey(EffectSchema.Literals([ "before", "after" ]))
        .annotateKey({
            default: "after",
            description: (
                "If specified and `\"after\"`, then the `\"prependedLines\"` will be " +
                "added *after* the lines created due to the value of the `\"disabledFormatters\"` " +
                "property.  Otherwise, the `\"prependedLines\"` will be placed at the *beginning* " +
                "of the file."
            ),
            title: "prependedLinesOrder"
        }),
    Providers: EffectSchema.Record(
        EffectSchema.String,
        EffectSchema.Union([ Provider, EffectSchema.Boolean ])
    )
        .annotateKey({
            description: (
                "A `Record<string, Provider>` (or `boolean`) that assigns per-provider configuration, " +
                "where the keys are the respective provider package names.  If a `boolean`, then the given " +
                "provider is enabled with default the options."
            ),
            title: "providers"
        }),
    TsConfigPath: EffectSchema.NonEmptyString
        .annotateKey({
            default: "tsconfig.json",
            description: "The path to your project's `tsconfig.json` file.",
            title: "tsconfigPath"
        })
}).annotate({
    description: (
        "The configuration that informs `code-auger` how and where it should generate the module " +
        "augmentations from your installed provider packages."
    ),
    identifier: "Config",
    title: "code-auger.config.json"
});

/**
 * The config of a given provider package specifies the types and export paths
 * relevant to generating the augmenting module for consumers that use the given
 * provider.
 */
export type Config = ConfigSchema<typeof Schema.Type>;

/* eslint-enable @typescript-eslint/typedef */
