/**
 *
 *
 * @module @sorrell/sorrell-wm-code-extension/Header
 * @internal
 *
 * @file      Header.ts
 * @author    Gage Sorrell <gage@sorrell.sh>
 * @copyright (c) 2026 Gage Sorrell
 * @license   MIT
 */

import { basename, isAbsolute, relative } from "node:path";

const ExtensionPattern: RegExp = /\.(?:tsx?|cc|cpp|cxx|h|hh|hpp|hxx|ixx|cppm|inl|ipp|tpp)$/iu;

/**
 * Determine whether a path points to a supported TypeScript or C++ source file.
 *
 * @param FilePath - The file-system path to inspect.
 * @returns {boolean} Whether the path has a supported source-file extension.
 */
export function IsSupportedSourcePath(FilePath: string): boolean
{
    return ExtensionPattern.test(FilePath);
}

/**
 * Derive the project's module name for a supported source file.
 *
 * @param FilePath - The source file's absolute or package-relative path.
 * @param PackageRootPath - The directory containing the nearest package.json.
 * @param PackageName - The nearest package.json's package name.
 * @returns {string} The package-qualified module name.
 */
export function DeriveModuleName(
    FilePath: string,
    PackageRootPath: string,
    PackageName: string
): string
{
    const RelativePath: string = relative(PackageRootPath, FilePath);
    const IsOutsidePackage: boolean =
        IsPathOutsidePackage(RelativePath) || isAbsolute(RelativePath);
    const PackageRelativePath: string = IsOutsidePackage
        ? basename(FilePath)
        : RelativePath;
    const PathParts: Array<string> = PackageRelativePath
        .split(/[\\/]/u)
        .filter((Part: string): boolean => Part.length > 0);
    const SourceIndex: number = PathParts.findIndex(
        (Part: string): boolean => /^(?:source|src)$/iu.test(Part)
    );
    const ModulePathParts: Array<string> = SourceIndex >= 0
        ? PathParts.slice(SourceIndex + 1)
        : PathParts;

    if (ModulePathParts.length > 0)
    {
        const FileNameIndex: number = ModulePathParts.length - 1;
        const FileName: string | undefined = ModulePathParts[FileNameIndex];

        if (FileName !== undefined)
        {
            const FileNameWithoutExtension: string = FileName.replace(ExtensionPattern, "");

            if (FileNameWithoutExtension.toLowerCase() === "index")
            {
                ModulePathParts.pop();
            }
            else
            {
                ModulePathParts[FileNameIndex] = FileNameWithoutExtension;
            }
        }
    }

    return [ PackageName, ...ModulePathParts ].join("/");
}

/**
 * Create the complete JSDoc header for a source file.
 *
 * @param FilePath - The source file path, used for its name and visibility.
 * @param ModuleName - The package-qualified module name.
 * @param CurrentYear - The copyright year.
 * @param NewLine - The document's newline sequence.
 * @returns {string} The generated header without a trailing newline.
 */
export function CreateHeader(
    FilePath: string,
    ModuleName: string,
    CurrentYear: number,
    NewLine: string = "\n"
): string
{
    const Lines: Array<string> = [
        "/**",
        " *",
        " *",
        ` * @module ${ModuleName}`
    ];

    if (FilePath.includes("Internal"))
    {
        Lines.push(" * @internal");
    }

    Lines.push(
        " *",
        ` * @file      ${basename(FilePath)}`,
        " * @author    Gage Sorrell <gage@sorrell.sh>",
        ` * @copyright (c) ${CurrentYear} Gage Sorrell`,
        " * @license   MIT",
        " */"
    );

    return Lines.join(NewLine);
}

/**
 * Detect a header previously generated by this extension.
 *
 * @param Content - The complete document text.
 * @returns {boolean} Whether the opening JSDoc block has module and file tags.
 */
export function HasGeneratedHeader(Content: string): boolean
{
    const ContentWithoutByteOrderMark: string = Content.startsWith("\uFEFF")
        ? Content.slice(1)
        : Content;
    const LeadingContent: string = ContentWithoutByteOrderMark.trimStart();

    if (!LeadingContent.startsWith("/**"))
    {
        return false;
    }

    const HeaderEnd: number = LeadingContent.indexOf("*/");

    if (HeaderEnd < 0)
    {
        return false;
    }

    const Header: string = LeadingContent.slice(0, HeaderEnd + 2);

    return Header.includes(" * @module ") && Header.includes(" * @file      ");
}

/**
 * Determine whether a relative path escapes its expected package root.
 *
 * @param RelativePath - The relative path to inspect.
 * @returns {boolean} Whether the path refers to a parent of the package root.
 */
function IsPathOutsidePackage(RelativePath: string): boolean
{
    return RelativePath === ".."
        || RelativePath.startsWith("..\\")
        || RelativePath.startsWith("../");
}
