/**
 * @file      Config.ts
 * @author    Gage Sorrell <gage@sorrell.sh>
 * @copyright (c) 2026 Gage Sorrell
 * @license   MIT
 */

import type { CodeFormatter, LineOrder } from "./Config.Types.js";
import { Config as EffectConfig, HashMap, type Option, pipe } from "effect";
import { IsConfigValid, IsProvider } from "./Config.Internal.js";
import { Code } from "@sorrell/cli-utilities/format";
import { CodeAugerText } from "../../Bin/Shared/Utility.js";
import type { ReadonlyRecord } from "effect/Record";

/**
 * Determine whether a given consumer {@link Config} is valid.  This performs checks on
 * the current filesystem, to check that provider dependencies are valid, *etc*.
 *
 * @param Argument - The `"code-auger"` property of a provider's `package.json`.
 *
 * @returns {In is ExportedType} Whether the given {@link Argument} of a provider is valid.
 */
export function IsValid(Argument: unknown): boolean
{
    if (!IsConfigValid(Argument))
    {
        return false;
    }

    // @TODO
    return true;
}

export const CodeFormatters: ReadonlyArray<CodeFormatter> =
    [
        "eslint",
        "ox",
        "prettier"
    ] as const;

/**
 * Check whether a given {@link Provider} defined in a consumer's {@link Config} is valid.
 *
 * @param Argument - The value that is checked for being a *valid* {@link Provider | provider config}
 * for the consumer.
 *
 * @returns {boolean} Whether the given {@link Argument} is a *valid* {@link Provider | provider config}
 * for the consumer.
 */
export function IsProviderValid(Argument: unknown): boolean
{
    return IsProvider(Argument);
}

/* eslint-disable @typescript-eslint/typedef */

const Provider: EffectConfig.Config<Provider> = EffectConfig.all({
    Enabled: pipe(
        EffectConfig.boolean("enabled"),
        EffectConfig.withDefault(true),
        EffectConfig.withDescription(
            `Whether ${ CodeAugerText } should generate this provider's module.  ` +
            `The default value is ${ Code("true") }.`
        )
    ),
    Watch: pipe(
        EffectConfig.boolean("enabled"),
        EffectConfig.withDefault(true),
        EffectConfig.withDescription(
            `Whether this provider's module should be generated by ${ CodeAugerText } when ` +
            `the ${ Code("--watch") } flag is specified.  The default value is ${ Code("true") }.`
        )
    )
});

export const Config: EffectConfig.Config<Config> = EffectConfig.all({
    BasePath: pipe(
        EffectConfig.nonEmptyString("BasePath"),
        EffectConfig.withDescription(
            `The directory path in which ${ CodeAugerText } will write the modules ` +
            "generated by your installed providers."
        )
    ),
    DisabledFormatters: pipe(
        EffectConfig.array(
            EffectConfig.literal(...CodeFormatters)("DisabledFormatters")
        ),
        EffectConfig.option,
        EffectConfig.withDescription(
            `If specified, the formatters/linters that ${ CodeAugerText } will ` +
            `disable for its generated modules.  Both ${ Code("eslint") } and ${ Code("oxfmt") }` +
            `/${ Code("oxlint") } be disabled via top-level comments.`
        )
    ),
    PrependedLines: pipe(
        EffectConfig.array(EffectConfig.string(), "prependedLines"),
        EffectConfig.option,
        EffectConfig.withDescription(
            "If specified, these lines of text will be prepended to all " +
            `modules generated by ${ CodeAugerText }.`
        )
    ),
    PrependedLinesOrder: pipe(
        EffectConfig.literal("before", "after")("prependedLinesOrder"),
        EffectConfig.withDefault("after"),
        EffectConfig.withDescription(
            ""
            // `If specified and ${ Code("after") }, then the ${ Code("prependedLines") } will be ` +
            // `added ${ Chalk.italic("after") } the lines created due to the value of the ` +
            // `${ Code("disabledFormatters") } property.  Otherwise, the ` +
            // `${ Code("prependedLines") } will be placed at the beginning of the file.`
        )
    ),
    Providers: pipe(
        EffectConfig.hashMap(
            pipe(
                EffectConfig.boolean(),
                EffectConfig.orElse(() => Provider)
            ),
            "providers"
        ),
        EffectConfig.map((Argument: HashMap.HashMap<string, boolean | Provider>) =>
        {
            return Object.fromEntries(HashMap.entries(Argument));
        })
    ),
    TsConfigPath: pipe(
        EffectConfig.nonEmptyString("tsConfigPath"),
        EffectConfig.withDefault("tsconfig.json"),
        EffectConfig.withDescription(
            `The path to your project's ${ Code("tsconfig.json") } file.`
        )
    ),
    "~Schema": pipe(
        EffectConfig.nonEmptyString("$schema"),
        EffectConfig.withDefault("code-auger/schema"),
        EffectConfig.withDescription(
            `The ${ Code("JSON") } schema for this config file.`
        )
    )
});

/* eslint-enable @typescript-eslint/typedef */

/**
 * The default object exported by `code-auger.config.ts`.
 *
 * @property {string} BasePath - The path to the directory in which
 * modules generated by providers will be written.
 *
 * @property {string} TsConfigPath - If specified, the path to the TypeScript Config file.
 * Otherwise, {@link findConfigFile} is called, with the path to your package's root directory
 * and default `tsconfig.json` file name.
 *
 * @property {ReadonlyArray<CodeFormatter>} DisabledFormatters - The
 * {@link CodeFormatter | code formatters/linters} to disable in auto-generated modules, via
 * comments at the top of the module, per the respective formatter's or linter's convention for
 * disabling at module scope.
 *
 * @property {ReadonlyArray<string>} PrependedLines - Lines to prepend to all modules.  This allows,
 * for example, behavior similar to the behavior afforded by {@link DisabledFormatters}.
 *
 * @property {Readonly<Record<string, Provider>>} Providers - A {@link Record} that assigns per-provider
 * configuration, where the keys are the respective provider package names.
 */
export interface Config
{
    readonly BasePath: string;
    readonly TsConfigPath?: string;
    readonly DisabledFormatters: Option.Option<ReadonlyArray<CodeFormatter>>;
    readonly PrependedLines: Option.Option<ReadonlyArray<string>>;
    readonly PrependedLinesOrder?: LineOrder;
    readonly Providers: ReadonlyRecord<string, boolean | Provider>;
    readonly "~Schema": string;
}

/**
 * For a given consumer and given provider, the consumer's configuration of that provider.
 *
 * @property {boolean} Enabled - Whether the provider's augmentation is disabled when
 * `code-auger generate` runs.  The default is `true`.
 *
 * @property {boolean} Watch - Whether `code-auger` should regenerate the given provider's
 * module when the `generate` command is run with the `--watch` option.  The default is `true`.
 */
export interface Provider
{
    readonly Enabled?: boolean;
    readonly Watch?: boolean;
}
