/**
 * @file      Config.Types.ts
 * @author    Gage Sorrell <gage@sorrell.sh>
 * @copyright (c) 2026 Gage Sorrell
 * @license   MIT
 */

/* eslint-disable-next-line @typescript-eslint/no-unused-vars */
import type { findConfigFile } from "typescript";

/** The formatters and linters that can be disabled via {@link Config!DisabledFormatters}. */
export type CodeFormatter =
    | "eslint"
    | "ox"
    | "prettier";

/**
 * For a given consumer and given provider, the consumer's configuration of that provider.
 *
 * @property {boolean} Disabled - Whether the provider's augmentation is disabled when
 * `code-auger generate` runs.
 *
 * @property {string} Path - The path, relative to the {@link Config!BasePath | configuration's base path},
 * to where the provider's generated module will be written.
 */
export type Provider =
    Readonly<Partial<{
        Disabled: boolean;
        Path: string;
    }>>;

/**
 * The default object exported by `code-auger.config.ts`.
 *
 * @property {string} BasePath - The path to the directory in which
 * modules generated by providers will be written.
 * 
 * @property {string} TsConfigPath - If specified, the path to the TypeScript Config file.
 * Otherwise, {@link findConfigFile} is called, with the path to your package's root directory
 * and default `tsconfig.json` file name.
 * 
 * @property {ReadonlyArray<CodeFormatter>} DisabledFormatters - The
 * {@link CodeFormatter | code formatters/linters} to disable in auto-generated modules, via
 * comments at the top of the module, per the respective formatter's or linter's convention for
 * disabling at module scope.
 * 
 * @property {ReadonlyArray<string>} PrependedLines - Lines to prepend to all modules.  This allows,
 * for example, behavior similar to the behavior afforded by {@link DisabledFormatters}.
 * 
 * @property {Readonly<Record<string, Provider>>} Providers - A {@link Record} that assigns per-provider
 * configuration, where the keys are the respective provider package names.
 */
export type Config =
    Readonly<{
        BasePath: string;
        TsConfigPath?: string;
        DisabledFormatters?: ReadonlyArray<CodeFormatter>;
        PrependedLines?: ReadonlyArray<string>;
        Providers: Readonly<Record<string, Provider>>;
    }>;
